### ISSUE TITLE
Plugin does not work with Logstash 5

### ISSUE THREAD

**Issue by ulf-de** [mehmetc/logstash-filter-private_geoip#1]
Hello, it seems like the plugin does not work anymore with logstash 5.

# /usr/share/logstash/bin/logstash-plugin install logstash-filter-private_geoip
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
Validating logstash-filter-private_geoip
Installing logstash-filter-private_geoip
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.0.2)`

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.0.2) java

    logstash-filter-private_geoip (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

The solution might be to use
`s.add_runtime_dependency "logstash-core-plugin-api", ">= 1.60", "<= 2.99"`

**Comment by mehmetc** [comment]
I know it has been a long but if you are still interested. Updated to the latest version of Logstash.
